namespace WarpBusiness.Employees.Models;

public record CreateEmployeeRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string Email,
    string? Phone,
    DateOnly? DateOfBirth,
    DateOnly HireDate,
    string? Department,
    string? JobTitle,
    Guid? ManagerId,
    EmploymentStatus EmploymentStatus,
    EmploymentType EmploymentType,
    Guid? UserId,
    decimal PayAmount,
    PayType PayType,
    string? Currency = null);

public record UpdateEmployeeRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string Email,
    string? Phone,
    DateOnly? DateOfBirth,
    DateOnly HireDate,
    DateOnly? TerminationDate,
    string? Department,
    string? JobTitle,
    Guid? ManagerId,
    EmploymentStatus EmploymentStatus,
    EmploymentType EmploymentType,
    Guid? UserId,
    decimal PayAmount,
    PayType PayType,
    string Currency);

public record EmployeeResponse(
    Guid Id,
    string EmployeeNumber,
    string FirstName,
    string LastName,
    string? MiddleName,
    string Email,
    string? Phone,
    DateOnly? DateOfBirth,
    DateOnly HireDate,
    DateOnly? TerminationDate,
    string? Department,
    string? JobTitle,
    Guid? ManagerId,
    EmploymentStatus EmploymentStatus,
    EmploymentType EmploymentType,
    Guid? UserId,
    Guid TenantId,
    decimal PayAmount,
    PayType PayType,
    string Currency,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record OrgChartNodeResponse(
    Guid Id,
    string EmployeeNumber,
    string FirstName,
    string LastName,
    string? JobTitle,
    string? Department,
    Guid? ManagerId,
    EmploymentStatus EmploymentStatus);
