namespace WarpBusiness.Shared.Catalog;

public record ProductDto(
    Guid Id,
    string Name,
    string? ShortDescription,
    string? Sku,
    string? Brand,
    string ProductType,
    string Status,
    decimal BasePrice,
    string Currency,
    Guid? CategoryId,
    string? CategoryName,
    string? PrimaryImageUrl,
    int VariantCount,
    int ImageCount,
    DateTimeOffset CreatedAt);

public record ProductDetailDto(
    Guid Id,
    string Name,
    string? Description,
    string? ShortDescription,
    string? Slug,
    string? Sku,
    string? Barcode,
    string? Brand,
    string? Manufacturer,
    Guid? CategoryId,
    string? CategoryName,
    string ProductType,
    string Status,
    decimal BasePrice,
    decimal? CompareAtPrice,
    decimal? CostPrice,
    string Currency,
    decimal? Weight,
    string? WeightUnit,
    decimal? Length,
    decimal? Width,
    decimal? Height,
    string? DimensionUnit,
    bool IsTaxable,
    string? TaxCode,
    string? MetaTitle,
    string? MetaDescription,
    string? Tags,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    IReadOnlyList<ProductOptionDto> Options,
    IReadOnlyList<ProductVariantDto> Variants,
    IReadOnlyList<ProductImageDto> Images,
    IReadOnlyList<ProductIngredientDto> Ingredients);

public record CreateProductRequest(
    string Name,
    string? Description,
    string? ShortDescription,
    string? Slug,
    string? Sku,
    string? Barcode,
    string? Brand,
    string? Manufacturer,
    Guid? CategoryId,
    string ProductType = "General",
    string Status = "Draft",
    decimal BasePrice = 0,
    decimal? CompareAtPrice = null,
    decimal? CostPrice = null,
    string Currency = "USD",
    decimal? Weight = null,
    string? WeightUnit = null,
    decimal? Length = null,
    decimal? Width = null,
    decimal? Height = null,
    string? DimensionUnit = null,
    bool IsTaxable = true,
    string? TaxCode = null,
    string? MetaTitle = null,
    string? MetaDescription = null,
    string? Tags = null);

public record UpdateProductRequest(
    string Name,
    string? Description,
    string? ShortDescription,
    string? Slug,
    string? Sku,
    string? Barcode,
    string? Brand,
    string? Manufacturer,
    Guid? CategoryId,
    string ProductType,
    string Status,
    decimal BasePrice,
    decimal? CompareAtPrice,
    decimal? CostPrice,
    string Currency,
    decimal? Weight,
    string? WeightUnit,
    decimal? Length,
    decimal? Width,
    decimal? Height,
    string? DimensionUnit,
    bool IsTaxable,
    string? TaxCode,
    string? MetaTitle,
    string? MetaDescription,
    string? Tags);
