// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarpBusiness.Scheduling.Data;

#nullable disable

namespace WarpBusiness.Scheduling.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260418090257_AddEmployeePositionsAvailabilityAndTimeOff")]
    partial class AddEmployeePositionsAvailabilityAndTimeOff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.BreakRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdditionalBreakAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("BreakDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("CountsAsHoursWorked")
                        .HasColumnType("boolean");

                    b.Property<int?>("FrequencyMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWaivable")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxConsecutiveMinutesWithoutBreak")
                        .HasColumnType("integer");

                    b.Property<int>("MinShiftMinutesToTrigger")
                        .HasColumnType("integer");

                    b.Property<int?>("MustStartAfterShiftMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MustStartBeforeShiftMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("OvertimeExtraBreakAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("State", "RuleType");

                    b.ToTable("BreakRules", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.EmployeeAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("EarliestStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("LatestEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "DayOfWeek")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "TenantId");

                    b.ToTable("EmployeeAvailabilities", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.EmployeePosition", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId", "PositionId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TenantId");

                    b.ToTable("EmployeePositions", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique();

                    b.ToTable("Positions", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkLocationId", "StartDate", "EndDate");

                    b.ToTable("Schedules", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("ActualEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ActualStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("BreakType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("ScheduledEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ScheduledStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasTaken")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("ScheduleBreaks", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("ActualEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ActualStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("ScheduledEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("ScheduledStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "Date");

                    b.ToTable("ScheduleShifts", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkLocationId");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique();

                    b.ToTable("ScheduleTemplates", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.StaffingBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "PositionId", "DayOfWeek", "StartTime");

                    b.ToTable("StaffingBlocks", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.TimeOffRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EmployeeId", "Status");

                    b.ToTable("TimeOffRequests", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.WorkLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique();

                    b.ToTable("WorkLocations", "scheduling");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.EmployeePosition", b =>
                {
                    b.HasOne("WarpBusiness.Scheduling.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.Schedule", b =>
                {
                    b.HasOne("WarpBusiness.Scheduling.Models.WorkLocation", "WorkLocation")
                        .WithMany("Schedules")
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleBreak", b =>
                {
                    b.HasOne("WarpBusiness.Scheduling.Models.ScheduleShift", "Shift")
                        .WithMany("Breaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleShift", b =>
                {
                    b.HasOne("WarpBusiness.Scheduling.Models.Schedule", "Schedule")
                        .WithMany("Shifts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleTemplate", b =>
                {
                    b.HasOne("WarpBusiness.Scheduling.Models.WorkLocation", "WorkLocation")
                        .WithMany("ScheduleTemplates")
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.StaffingBlock", b =>
                {
                    b.HasOne("WarpBusiness.Scheduling.Models.ScheduleTemplate", "Template")
                        .WithMany("StaffingBlocks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.Schedule", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleShift", b =>
                {
                    b.Navigation("Breaks");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.ScheduleTemplate", b =>
                {
                    b.Navigation("StaffingBlocks");
                });

            modelBuilder.Entity("WarpBusiness.Scheduling.Models.WorkLocation", b =>
                {
                    b.Navigation("ScheduleTemplates");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
