namespace WarpBusiness.Shared.Invoicing;

public record InvoiceDto(
    Guid Id,
    string InvoiceNumber,
    Guid? CompanyId,
    string? CompanyName,
    Guid? ContactId,
    string? ContactName,
    DateOnly IssueDate,
    DateOnly DueDate,
    decimal TotalAmount,
    decimal AmountPaid,
    decimal BalanceDue,
    string Currency,
    string Status,
    int LineItemCount,
    DateTimeOffset CreatedAt);

public record InvoiceDetailDto(
    Guid Id,
    string InvoiceNumber,
    Guid? CompanyId,
    string? CompanyName,
    Guid? ContactId,
    string? ContactName,
    string? BillingAddress,
    string? ShippingAddress,
    DateOnly IssueDate,
    DateOnly DueDate,
    DateOnly? PaidDate,
    string? PaymentTerms,
    decimal Subtotal,
    decimal DiscountAmount,
    decimal TaxAmount,
    decimal TotalAmount,
    decimal AmountPaid,
    decimal BalanceDue,
    string Currency,
    decimal? DiscountPercent,
    decimal? DiscountFixed,
    decimal? TaxRate,
    string Status,
    string? Notes,
    string? CustomerNotes,
    string? FooterText,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string CreatedBy,
    IReadOnlyList<InvoiceLineItemDto> LineItems,
    IReadOnlyList<InvoicePaymentDto> Payments);

public record CreateInvoiceRequest(
    Guid? CompanyId = null,
    string? CompanyName = null,
    Guid? ContactId = null,
    string? ContactName = null,
    string? BillingAddress = null,
    string? ShippingAddress = null,
    DateOnly? IssueDate = null,
    DateOnly? DueDate = null,
    string? PaymentTerms = null,
    string Currency = "USD",
    decimal? DiscountPercent = null,
    decimal? DiscountFixed = null,
    decimal? TaxRate = null,
    string? Notes = null,
    string? CustomerNotes = null,
    string? FooterText = null,
    IReadOnlyList<CreateInvoiceLineItemRequest>? LineItems = null);

public record UpdateInvoiceRequest(
    Guid? CompanyId,
    string? CompanyName,
    Guid? ContactId,
    string? ContactName,
    string? BillingAddress,
    string? ShippingAddress,
    DateOnly IssueDate,
    DateOnly DueDate,
    string? PaymentTerms,
    string Currency,
    decimal? DiscountPercent,
    decimal? DiscountFixed,
    decimal? TaxRate,
    string? Notes,
    string? CustomerNotes,
    string? FooterText);

public record InvoiceSummaryDto(
    int TotalInvoices,
    int DraftCount,
    int SentCount,
    int OverdueCount,
    int PaidCount,
    decimal TotalOutstanding,
    decimal TotalOverdue,
    decimal TotalPaidThisMonth);
