apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warp-ingress
  namespace: warp-business
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: api.warp-business.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: warp-api
            port:
              number: 8080
  - host: app.warp-business.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: warp-web
            port:
              number: 8080
  - host: portal.warp-business.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: warp-portal
            port:
              number: 8080
