// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarpBusiness.Catalog.Data;

#nullable disable

namespace WarpBusiness.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarpBusiness.Catalog.Models.CatalogNotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Notations", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_TenantId_Name_Root")
                        .HasFilter("\"ParentCategoryId\" IS NULL");

                    b.HasIndex("TenantId", "ParentCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_TenantId_Parent_Name")
                        .HasFilter("\"ParentCategoryId\" IS NOT NULL");

                    b.ToTable("Categories", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("SKU", "TenantId")
                        .IsUnique()
                        .HasFilter("\"SKU\" IS NOT NULL");

                    b.ToTable("Products", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasFilter("\"ProductId\" IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("VariantId")
                        .HasFilter("\"VariantId\" IS NOT NULL");

                    b.ToTable("ProductMedia", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductNotation", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotationId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "NotationId");

                    b.HasIndex("NotationId");

                    b.ToTable("ProductNotations", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVariantAxis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("ProductOptions", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("OptionId", "Value")
                        .IsUnique();

                    b.ToTable("ProductOptionValues", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductTaxonomyAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NumberValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MappingId");

                    b.HasIndex("MappingId", "AttributeId")
                        .IsUnique();

                    b.ToTable("ProductTaxonomyAttributeValues", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductTaxonomyMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeFullPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TaxonomyNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductId", "ProviderKey", "TaxonomyNodeId")
                        .IsUnique();

                    b.ToTable("ProductTaxonomyMappings", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PriceAdjustmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("SKU", "TenantId")
                        .IsUnique()
                        .HasFilter("\"SKU\" IS NOT NULL");

                    b.ToTable("ProductVariants", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.VariantOptionValue", b =>
                {
                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionValueId")
                        .HasColumnType("uuid");

                    b.HasKey("VariantId", "OptionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("OptionValueId");

                    b.ToTable("VariantOptionValues", "catalog");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.Category", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.Product", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductMedia", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.Product", "Product")
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WarpBusiness.Catalog.Models.ProductVariant", "Variant")
                        .WithMany("Media")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductNotation", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.CatalogNotation", "Notation")
                        .WithMany("ProductNotations")
                        .HasForeignKey("NotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarpBusiness.Catalog.Models.Product", "Product")
                        .WithMany("Notations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductOption", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.Product", "Product")
                        .WithMany("Options")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductOptionValue", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.ProductOption", "Option")
                        .WithMany("Values")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductTaxonomyAttributeValue", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.ProductTaxonomyMapping", "Mapping")
                        .WithMany("AttributeValues")
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductTaxonomyMapping", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.Product", "Product")
                        .WithMany("TaxonomyMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductVariant", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.VariantOptionValue", b =>
                {
                    b.HasOne("WarpBusiness.Catalog.Models.ProductOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarpBusiness.Catalog.Models.ProductOptionValue", "OptionValue")
                        .WithMany("VariantValues")
                        .HasForeignKey("OptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarpBusiness.Catalog.Models.ProductVariant", "Variant")
                        .WithMany("OptionValues")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("OptionValue");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.CatalogNotation", b =>
                {
                    b.Navigation("ProductNotations");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.Product", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Notations");

                    b.Navigation("Options");

                    b.Navigation("TaxonomyMappings");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductOption", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductOptionValue", b =>
                {
                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductTaxonomyMapping", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("WarpBusiness.Catalog.Models.ProductVariant", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("OptionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
