apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-web
  namespace: warp-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp-web
  template:
    metadata:
      labels:
        app: warp-web
    spec:
      containers:
      - name: warp-web
        image: warp-business/web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: warp-web-config
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
