apiVersion: v1
kind: Service
metadata:
  name: warp-postgres
  namespace: warp-business
spec:
  selector:
    app: warp-postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None  # headless for StatefulSet
