apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: warp-postgres
  namespace: warp-business
spec:
  selector:
    matchLabels:
      app: warp-postgres
  serviceName: warp-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: warp-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: warpbusiness
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: warp-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: warp-secrets
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: [pg_isready, -U, warpuser, -d, warpbusiness]
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
